# Generated by Django 5.2.12 on 2026-06-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_student_studentprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentProfile",
        ),
    ]
